### ISSUE TITLE
Doesn't compile in Visual Studio in Windows

### ISSUE THREAD

**Issue by matizzy** [panazzo/corerestclient#3]
To be able to compile in windows, dependencies need to be added.

**Comment by matizzy** [comment]
I created a pull request to add windows compatibility

**Comment by panazzo** [comment]
Have you tried to open it as a .net core project?

**Comment by matizzy** [comment]
Hmm it looks like I actually didn't have an updated version of visual studio and the .net core tooling in my windows partition so that could have been the issue. 

I'll see what happens after I update it.

**Comment by matizzy** [comment]
looks like it wasn't necessary after updating my .Net core tooling
