### ISSUE TITLE
Support JWT authentication 

### ISSUE THREAD

**Issue by panazzo** [panazzo/corerestclient#5]
Add optional support to JWT authentication

**Comment by QzSG** [comment]
I would be interested in doing this. 

Would send in a pull request in a while.

**Comment by QzSG** [comment]
Is there a reason why it's closed?  It works as intended. Currently your rest client only works for rest apis using old http basic authentication

**Comment by panazzo** [comment]
I'm sorry, there was a problem while merging your PR and I've refused it by mistake.
Could you please submit it again?

Thank you very much

**Comment by QzSG** [comment]
Hope you are still receiving notifications, I sent another merge request after adding all your other merged PRs

**Comment by QzSG** [comment]
@panazzo Not sure how u got the dll in the lib folder, I copied mine from bin/debug, hope its the same one. Would be nice for u to add in readme how to open the source code, i simply open project.json under open project in vs 2015

**Comment by panazzo** [comment]
@QzSG Thank you once again for your PR.
The whole thing about the lib folder is in order to pack for Nuget. I also open the project using VS 2015 or VS Code.
I'll try to figure out if there's another option for Nuget Packages.
