### ISSUE TITLE
Reuse httpclient

### ISSUE THREAD

**Issue by Tazer** [panazzo/corerestclient#7]
Hey! :)

Was looking at your code and I see that you instantiate a new httpclient for each call. 
Maybe it should reuse the httpclient instead: http://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/

**Comment by panazzo** [comment]
Great tip :) Thank you very much! Wanna PR? I'll open this isue

**Comment by feeeper** [comment]
@Tazer If you're not interested in it so I can resolve that issue

**Comment by Tazer** [comment]
@feeper feel free to finish the issue :)
